### ISSUE TITLE
Calculating the score?

### ISSUE THREAD

**Issue by petteriTeikari** [oussamabonnor1/Rocket_Ride_Unity2D#1]
Thanks for making the game public @oussamabonnor1 :)

I had a bit of issues as an Unity noobie in understanding how the score is actually calculated as it was not found from the scripts at all?

**Comment by oussamabonnor1** [comment]
First of all, thank you for trying the game and allow me to unofficially welcome you to the Unity world, I'm sure you'll enjoy it. 
The score has a direct relationship with how far the player has gone, which is why I attached it to the camera behavior (the worst possible place to attach it, I know. But this game was a side project that I did in a day so 😄).
The [function.]( https://github.com/oussamabonnor1/Rocket_Ride_Unity2D/blob/master/Assets/Scripts/CameraBehaviour.cs#L19)

The exact code is 
```
score += Time.deltaTime * 15f;
scoreText.text = "Score: "+ (int) score;
```
If you have other questions, let me know. Also, all PRs are more than welcome if you want to contribute 👀

**Comment by petteriTeikari** [comment]
Thanks for the quick reply @oussamabonnor1, and was yes a bit puzzled as wanted to play with the game and add some features like adding extra items that you either want to catch or avoid (http://xrayisgray.de/sites/tutorial_1.html), and then could not figure where in code to add that.

**Comment by oussamabonnor1** [comment]
I hope you can do that with ease now, if you have any other questions feel free to re-open this issue! Good luck.
